# 这个是我们通用的这个超参数管理和设置，不包括具体的模型超参数
defaults:
  # 可选模型: model1, model2, rnn, gru, lstm, transformer（对应 config/models/ 下的配置）
  - model: transformer
  - _self_

# 数据配置
data:
  data_dir: "dataset\\data.csv"
  batch_size: 128
  train_ratio: 0.8
  random_state: 42
  window_size: 15
# 训练配置
training:
  learning_rate: 0.001
  epochs: 150
  weight_decay: 5e-5
  early_stop_patience: 20
  task_type : classification # 默认分类任务
# 设备配置
device: "cuda"
best_model_path: "checkpoints/best_${hydra:runtime.choices.model}_model.pth"  # 随所选模型名自动生成 # 这个是我们的模型参数保存的地址，方便我们后续断点恢复之类的
log_path : "result"