# 这个是我们通用的这个超参数管理和设置，不包括具体的模型超参数
defaults:
  # 可选模型: model1, model2, rnn, gru, lstm, transformer（对应 config/models/ 下的配置）
  - model: transformer
  - training_loop : default
  - trainer : base
  - _self_
# 设备配置
data_dir: "dataset\\data.csv"
device: "cuda"
best_model_path: "checkpoints/best_${hydra:runtime.choices.model}_model.pth"  # 随所选模型名自动生成 # 这个是我们的模型参数保存的地址，方便我们后续断点恢复之类的
log_path : "result"